import type { OrderRow } from '@/types/database'

/** Locale for customer-facing dates/times (UK). */
const LOCALE = 'en-GB'

function fallbackStamp(d: Date): string {
  return d.toLocaleString(LOCALE, {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

/** "29 Apr 2026, 14:32" — for order history / audit views (not basket names). */
export function formatOrderTimestampLabel(iso: string): string {
  return fallbackStamp(new Date(iso))
}

/** Legacy auto names and duplicate suffixes — not shown as the customer's basket label. */
export function isAutoGeneratedBasketReference(ref: string | null | undefined): boolean {
  const t = (ref ?? '').trim()
  if (!t) return true
  if (/^Basket · /i.test(t)) return true
  if (/^Copy · /i.test(t)) return true
  return false
}

/** User-chosen basket label without system suffixes like " (copy)". */
export function sanitizeBasketReferenceForDisplay(ref: string | null | undefined): string | null {
  const t = (ref ?? '').trim()
  if (!t || isAutoGeneratedBasketReference(t)) return null
  const withoutCopy = t.replace(/\s*\(copy\)\s*$/i, '').trim()
  return withoutCopy || null
}

type BasketLabelOrder = Pick<OrderRow, 'id' | 'reference' | 'created_at'>

/**
 * Human-friendly basket labels for drafts. Same base name → "Kitchen A (2)" only when needed.
 * Unnamed baskets → "Basket 1", "Basket 2", … by creation order.
 */
export function buildBasketDisplayLabels(orders: BasketLabelOrder[]): Map<string, string> {
  const sorted = [...orders].sort(
    (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
  )
  const labels = new Map<string, string>()
  const nameCounts = new Map<string, number>()
  let unnamedCounter = 0

  for (const o of sorted) {
    const base = sanitizeBasketReferenceForDisplay(o.reference)
    if (base) {
      const key = base.toLowerCase()
      const count = (nameCounts.get(key) ?? 0) + 1
      nameCounts.set(key, count)
      labels.set(o.id, count > 1 ? `${base} (${count})` : base)
    } else {
      unnamedCounter += 1
      labels.set(o.id, `Basket ${unnamedCounter}`)
    }
  }
  return labels
}

export function getBasketDisplayLabel(
  order: BasketLabelOrder,
  labels?: Map<string, string>,
): string {
  return labels?.get(order.id) ?? sanitizeBasketReferenceForDisplay(order.reference) ?? 'Basket'
}

/**
 * Labels a basket or order when no custom reference is stored.
 * Draft baskets use neutral fallbacks; placed orders may show a created timestamp.
 */
export function formatOrderReferenceOrFallback(
  order: Pick<OrderRow, 'id' | 'reference' | 'created_at' | 'status'>,
): string {
  const ref = sanitizeBasketReferenceForDisplay(order.reference)
  if (ref) return ref
  if (order.status === 'draft') return 'Basket'
  const when = formatOrderTimestampLabel(order.created_at)
  return `Order · ${when}`
}

/** @deprecated New drafts use `reference: null`; display names come from {@link buildBasketDisplayLabels}. */
export function defaultNewDraftBasketReference(): string {
  return ''
}
